GET http://localhost:5000/ads

###

GET http://localhost:5000/ads/22


###

GET http://localhost:5000/ads?categoryIn=2,1&orderByTitle=DESC

###

GET http://localhost:5000/ads/search?title=bike

###

GET http://localhost:5000/ads/sort-by-date?sortOrder=desc

###

POST http://localhost:5000/ads
Content-Type: application/json

{
  "title": "Book to sell",
  "description": "My book is a good book",
  "owner": "book@gmail.com",
  "price": 50,
  "imgUrl": "picture.jpg",
  "location": "Somewhere",
  "createdAt": "2023-09-20",
  "category": { "id": 3 }, 
  "tags": [{ "id" : 1}]
}

###

POST http://localhost:5000/ads/search
Content-Type: application/json

{
  "title": "bike"
}

###

POST http://localhost:5000/reset

###

DELETE http://localhost:5000/ads/22

###

DELETE http://localhost:5000/ads

###

PATCH http://localhost:5000/ads/21
// Mise à jour partielle de l'objet
Content-Type: application/json

{
  "imgUrl" : "https://cdn.pixabay.com/photo/2018/01/17/18/43/book-3088775_1280.jpg"
}

###

GET http://localhost:5000/categories

###

GET http://localhost:5000/categories/3

###

GET http://localhost:5000/categories/3/ads

###

POST http://localhost:5000/categories
Content-Type: application/json

{
  "name": "Ameublement"
}

###
PATCH http://localhost:5000/categories/4
Content-Type: application/json

{
  "name": "Vacances"
}

###
DELETE http://localhost:5000/categories/4

### Tags - getAll

GET http://localhost:5000/tags

### Tags - createOne
POST http://localhost:5000/tags
content-type: application/json

{
  "name": "Bon état"
}